# Generated by Django 2.2.28 on 2023-01-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20230114_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='exit'),
            preserve_default=False,
        ),
    ]
